version: "3"
services:

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: workopia-web:1.0
    ports:
      - "8000:80"
    # depends_on:
    #   - db
    volumes:
      - /var/www/html/vendor
      - ../:/var/www/html
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG:
        client_host=host.docker.internal
        start_with_request=yes

  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: workopia
      MYSQL_USER: Giga
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
    restart: unless-stopped
      
  phpmyadmin:
    # depends_on:
    #   - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"

volumes:
  mysql-data:
    driver: local
    
